spring:
  datasource:
    password: ${MYSQL_PASSWORD}
    username: ${MYSQL_USER}
    url: ${APP_DATABASE_CONNECTION_STRING}


  jpa:
    hibernate:
      ddl-auto: update
server:
  port: ${APP_PORT} 
  
